package com.zf.demo4jsp.entity;

import java.util.Date;

public class ClassIfication {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.parentId
     *
     * @mbggenerated
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification.creatime
     *
     * @mbggenerated
     */
    private Date creatime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated
     */
    public ClassIfication(Integer id, String name, String parentid, Date creatime) {
        this.id = id;
        this.name = name;
        this.parentid = parentid;
        this.creatime = creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated
     */
    public ClassIfication() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.id
     *
     * @return the value of classification.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.id
     *
     * @param id the value for classification.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.name
     *
     * @return the value of classification.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.name
     *
     * @param name the value for classification.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.parentId
     *
     * @return the value of classification.parentId
     *
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.parentId
     *
     * @param parentid the value for classification.parentId
     *
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification.creatime
     *
     * @return the value of classification.creatime
     *
     * @mbggenerated
     */
    public Date getCreatime() {
        return creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification.creatime
     *
     * @param creatime the value for classification.creatime
     *
     * @mbggenerated
     */
    public void setCreatime(Date creatime) {
        this.creatime = creatime;
    }
}