package com.zf.demo4jsp.entity;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderNumber
     *
     * @mbggenerated
     */
    private String ordernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderName
     *
     * @mbggenerated
     */
    private String ordername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderAmount
     *
     * @mbggenerated
     */
    private String orderamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderTime
     *
     * @mbggenerated
     */
    private Date ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.userId
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.paymentStatus
     *
     * @mbggenerated
     */
    private Integer paymentstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public Order(Integer id, String ordernumber, String ordername, String orderamount, Date ordertime, String userid, Integer paymentstatus) {
        this.id = id;
        this.ordernumber = ordernumber;
        this.ordername = ordername;
        this.orderamount = orderamount;
        this.ordertime = ordertime;
        this.userid = userid;
        this.paymentstatus = paymentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public Order() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderNumber
     *
     * @return the value of order.orderNumber
     *
     * @mbggenerated
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderNumber
     *
     * @param ordernumber the value for order.orderNumber
     *
     * @mbggenerated
     */
    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber == null ? null : ordernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderName
     *
     * @return the value of order.orderName
     *
     * @mbggenerated
     */
    public String getOrdername() {
        return ordername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderName
     *
     * @param ordername the value for order.orderName
     *
     * @mbggenerated
     */
    public void setOrdername(String ordername) {
        this.ordername = ordername == null ? null : ordername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderAmount
     *
     * @return the value of order.orderAmount
     *
     * @mbggenerated
     */
    public String getOrderamount() {
        return orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderAmount
     *
     * @param orderamount the value for order.orderAmount
     *
     * @mbggenerated
     */
    public void setOrderamount(String orderamount) {
        this.orderamount = orderamount == null ? null : orderamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderTime
     *
     * @return the value of order.orderTime
     *
     * @mbggenerated
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderTime
     *
     * @param ordertime the value for order.orderTime
     *
     * @mbggenerated
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.userId
     *
     * @return the value of order.userId
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.userId
     *
     * @param userid the value for order.userId
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.paymentStatus
     *
     * @return the value of order.paymentStatus
     *
     * @mbggenerated
     */
    public Integer getPaymentstatus() {
        return paymentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.paymentStatus
     *
     * @param paymentstatus the value for order.paymentStatus
     *
     * @mbggenerated
     */
    public void setPaymentstatus(Integer paymentstatus) {
        this.paymentstatus = paymentstatus;
    }
}