package com.zf.demo4jsp.entity;


public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.occupationType
     *
     * @mbggenerated
     */
    private Integer occupationtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.idCard
     *
     * @mbggenerated
     */
    private Integer idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.idNumber
     *
     * @mbggenerated
     */
    private String idnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.headPortrait
     *
     * @mbggenerated
     */
    private String headportrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.frontOfDocument
     *
     * @mbggenerated
     */
    private String frontofdocument;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.reverseOfDocuments
     *
     * @mbggenerated
     */
    private String reverseofdocuments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.beGoodAtShuShu
     *
     * @mbggenerated
     */
    private String begoodatshushu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.learningExperience
     *
     * @mbggenerated
     */
    private String learningexperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.practitionersYear
     *
     * @mbggenerated
     */
    private String practitionersyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.careerExperience
     *
     * @mbggenerated
     */
    private String careerexperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.field
     *
     * @mbggenerated
     */
    private String field;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.chargeSituation
     *
     * @mbggenerated
     */
    private String chargesituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.channel
     *
     * @mbggenerated
     */
    private Integer channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.weixin
     *
     * @mbggenerated
     */
    private String weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.salaryExpectation
     *
     * @mbggenerated
     */
    private String salaryexpectation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.alipayName
     *
     * @mbggenerated
     */
    private String alipayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.alipayAccount
     *
     * @mbggenerated
     */
    private String alipayaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.toExamine
     *
     * @mbggenerated
     */
    private Integer toexamine;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    public UserInfo(Integer userid, String username, String pwd, String nickname, Integer sex, String address, String city, String qq, String email, String phone, Integer occupationtype, Integer state, Integer idcard, String idnumber, String headportrait, String frontofdocument, String reverseofdocuments, String begoodatshushu, String title, String learningexperience, String practitionersyear, String careerexperience, String field, String chargesituation, Integer channel, String weixin, String salaryexpectation, String level, String alipayname, String alipayaccount, Integer toexamine) {
        this.userid = userid;
        this.username = username;
        this.pwd = pwd;
        this.nickname = nickname;
        this.sex = sex;
        this.address = address;
        this.city = city;
        this.qq = qq;
        this.email = email;
        this.phone = phone;
        this.occupationtype = occupationtype;
        this.state = state;
        this.idcard = idcard;
        this.idnumber = idnumber;
        this.headportrait = headportrait;
        this.frontofdocument = frontofdocument;
        this.reverseofdocuments = reverseofdocuments;
        this.begoodatshushu = begoodatshushu;
        this.title = title;
        this.learningexperience = learningexperience;
        this.practitionersyear = practitionersyear;
        this.careerexperience = careerexperience;
        this.field = field;
        this.chargesituation = chargesituation;
        this.channel = channel;
        this.weixin = weixin;
        this.salaryexpectation = salaryexpectation;
        this.level = level;
        this.alipayname = alipayname;
        this.alipayaccount = alipayaccount;
        this.toexamine = toexamine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    public UserInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userId
     *
     * @return the value of userinfo.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userId
     *
     * @param userid the value for userinfo.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userName
     *
     * @return the value of userinfo.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userName
     *
     * @param username the value for userinfo.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.pwd
     *
     * @return the value of userinfo.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.pwd
     *
     * @param pwd the value for userinfo.pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.nickname
     *
     * @return the value of userinfo.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.nickname
     *
     * @param nickname the value for userinfo.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.sex
     *
     * @return the value of userinfo.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.sex
     *
     * @param sex the value for userinfo.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.address
     *
     * @return the value of userinfo.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.address
     *
     * @param address the value for userinfo.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.city
     *
     * @return the value of userinfo.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.city
     *
     * @param city the value for userinfo.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.qq
     *
     * @return the value of userinfo.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.qq
     *
     * @param qq the value for userinfo.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.email
     *
     * @return the value of userinfo.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.email
     *
     * @param email the value for userinfo.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.phone
     *
     * @return the value of userinfo.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.phone
     *
     * @param phone the value for userinfo.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.occupationType
     *
     * @return the value of userinfo.occupationType
     *
     * @mbggenerated
     */
    public Integer getOccupationtype() {
        return occupationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.occupationType
     *
     * @param occupationtype the value for userinfo.occupationType
     *
     * @mbggenerated
     */
    public void setOccupationtype(Integer occupationtype) {
        this.occupationtype = occupationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.state
     *
     * @return the value of userinfo.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.state
     *
     * @param state the value for userinfo.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.idCard
     *
     * @return the value of userinfo.idCard
     *
     * @mbggenerated
     */
    public Integer getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.idCard
     *
     * @param idcard the value for userinfo.idCard
     *
     * @mbggenerated
     */
    public void setIdcard(Integer idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.idNumber
     *
     * @return the value of userinfo.idNumber
     *
     * @mbggenerated
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.idNumber
     *
     * @param idnumber the value for userinfo.idNumber
     *
     * @mbggenerated
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber == null ? null : idnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.headPortrait
     *
     * @return the value of userinfo.headPortrait
     *
     * @mbggenerated
     */
    public String getHeadportrait() {
        return headportrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.headPortrait
     *
     * @param headportrait the value for userinfo.headPortrait
     *
     * @mbggenerated
     */
    public void setHeadportrait(String headportrait) {
        this.headportrait = headportrait == null ? null : headportrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.frontOfDocument
     *
     * @return the value of userinfo.frontOfDocument
     *
     * @mbggenerated
     */
    public String getFrontofdocument() {
        return frontofdocument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.frontOfDocument
     *
     * @param frontofdocument the value for userinfo.frontOfDocument
     *
     * @mbggenerated
     */
    public void setFrontofdocument(String frontofdocument) {
        this.frontofdocument = frontofdocument == null ? null : frontofdocument.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.reverseOfDocuments
     *
     * @return the value of userinfo.reverseOfDocuments
     *
     * @mbggenerated
     */
    public String getReverseofdocuments() {
        return reverseofdocuments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.reverseOfDocuments
     *
     * @param reverseofdocuments the value for userinfo.reverseOfDocuments
     *
     * @mbggenerated
     */
    public void setReverseofdocuments(String reverseofdocuments) {
        this.reverseofdocuments = reverseofdocuments == null ? null : reverseofdocuments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.beGoodAtShuShu
     *
     * @return the value of userinfo.beGoodAtShuShu
     *
     * @mbggenerated
     */
    public String getBegoodatshushu() {
        return begoodatshushu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.beGoodAtShuShu
     *
     * @param begoodatshushu the value for userinfo.beGoodAtShuShu
     *
     * @mbggenerated
     */
    public void setBegoodatshushu(String begoodatshushu) {
        this.begoodatshushu = begoodatshushu == null ? null : begoodatshushu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.title
     *
     * @return the value of userinfo.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.title
     *
     * @param title the value for userinfo.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.learningExperience
     *
     * @return the value of userinfo.learningExperience
     *
     * @mbggenerated
     */
    public String getLearningexperience() {
        return learningexperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.learningExperience
     *
     * @param learningexperience the value for userinfo.learningExperience
     *
     * @mbggenerated
     */
    public void setLearningexperience(String learningexperience) {
        this.learningexperience = learningexperience == null ? null : learningexperience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.practitionersYear
     *
     * @return the value of userinfo.practitionersYear
     *
     * @mbggenerated
     */
    public String getPractitionersyear() {
        return practitionersyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.practitionersYear
     *
     * @param practitionersyear the value for userinfo.practitionersYear
     *
     * @mbggenerated
     */
    public void setPractitionersyear(String practitionersyear) {
        this.practitionersyear = practitionersyear == null ? null : practitionersyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.careerExperience
     *
     * @return the value of userinfo.careerExperience
     *
     * @mbggenerated
     */
    public String getCareerexperience() {
        return careerexperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.careerExperience
     *
     * @param careerexperience the value for userinfo.careerExperience
     *
     * @mbggenerated
     */
    public void setCareerexperience(String careerexperience) {
        this.careerexperience = careerexperience == null ? null : careerexperience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.field
     *
     * @return the value of userinfo.field
     *
     * @mbggenerated
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.field
     *
     * @param field the value for userinfo.field
     *
     * @mbggenerated
     */
    public void setField(String field) {
        this.field = field == null ? null : field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.chargeSituation
     *
     * @return the value of userinfo.chargeSituation
     *
     * @mbggenerated
     */
    public String getChargesituation() {
        return chargesituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.chargeSituation
     *
     * @param chargesituation the value for userinfo.chargeSituation
     *
     * @mbggenerated
     */
    public void setChargesituation(String chargesituation) {
        this.chargesituation = chargesituation == null ? null : chargesituation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.channel
     *
     * @return the value of userinfo.channel
     *
     * @mbggenerated
     */
    public Integer getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.channel
     *
     * @param channel the value for userinfo.channel
     *
     * @mbggenerated
     */
    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.weixin
     *
     * @return the value of userinfo.weixin
     *
     * @mbggenerated
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.weixin
     *
     * @param weixin the value for userinfo.weixin
     *
     * @mbggenerated
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.salaryExpectation
     *
     * @return the value of userinfo.salaryExpectation
     *
     * @mbggenerated
     */
    public String getSalaryexpectation() {
        return salaryexpectation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.salaryExpectation
     *
     * @param salaryexpectation the value for userinfo.salaryExpectation
     *
     * @mbggenerated
     */
    public void setSalaryexpectation(String salaryexpectation) {
        this.salaryexpectation = salaryexpectation == null ? null : salaryexpectation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.level
     *
     * @return the value of userinfo.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.level
     *
     * @param level the value for userinfo.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.alipayName
     *
     * @return the value of userinfo.alipayName
     *
     * @mbggenerated
     */
    public String getAlipayname() {
        return alipayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.alipayName
     *
     * @param alipayname the value for userinfo.alipayName
     *
     * @mbggenerated
     */
    public void setAlipayname(String alipayname) {
        this.alipayname = alipayname == null ? null : alipayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.alipayAccount
     *
     * @return the value of userinfo.alipayAccount
     *
     * @mbggenerated
     */
    public String getAlipayaccount() {
        return alipayaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.alipayAccount
     *
     * @param alipayaccount the value for userinfo.alipayAccount
     *
     * @mbggenerated
     */
    public void setAlipayaccount(String alipayaccount) {
        this.alipayaccount = alipayaccount == null ? null : alipayaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.toExamine
     *
     * @return the value of userinfo.toExamine
     *
     * @mbggenerated
     */
    public Integer getToexamine() {
        return toexamine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.toExamine
     *
     * @param toexamine the value for userinfo.toExamine
     *
     * @mbggenerated
     */
    public void setToexamine(Integer toexamine) {
        this.toexamine = toexamine;
    }
}